### ISSUE TITLE
How can I make the React Component tag Highlight like the normal html tag ?

### ISSUE THREAD

**Issue by uncledb** [rexebin/dracula#1]
In webstorm, the react component tag will show with color like html tag, just like div,span ...  In Vscode, Use dracule,  everything is beautiful, but the react component tag color does not like it in webstorm.  it is white in vscode , but it is yellow in webstorm. how to resolve it ?  

I can not find the document at Vscode website. 

Look forward to your favourable reply,  

thank you a lot

**Comment by rexebin** [comment]
Hi @uncledb , thanks for using the theme. Would you please send me a sample code and let me where to look? I will try to fix it and push an update.  If you are interested, I can show you how to inspect and fix the colour.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rexebin** [comment]
If it is html in js or jsx files, there are extensions for the problem. Please search for “inline”. With angular, I use angular2-inline, there is also another called inline-html. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by uncledb** [comment]
@rexebin 
```
import React from "react";
import { Button } from "antd";

const renderSomething = () => {
  return (
    <div>
      <Button>
           Button is white in vscode when use dracule,but is yellow in webstorm
      </Button>
    </div>
  );
};

```

thank you

**Comment by uncledb** [comment]
I had install the extensions, but not work yet. 
if I do not use dracule, It is highlight, So I think there is something forget adding in dracule theme file.
but I do not know witch field it is ...
