### ISSUE TITLE
Can the author provide a grey Orange theme

### ISSUE THREAD

**Issue by jahnli** [rexebin/dracula#3]
Can the author provide a grey Orange theme Or how to develop

[grey_orange.zip](https://github.com/rexebin/darcula/files/5382145/grey_orange.zip)

**Comment by rexebin** [comment]
Hi @jahnli , the theme is really easy to develop, all you have to do is to edit and update the colors in the json file in the theme folder, then edit the package.json file at the root folder, then you publish to vs code extension. 

It is extremely easy to fine tune your theme, just use  “Developer: Inspect TM Scopes” function in vscode to get the scope and add color configurations in the json file.

Here is a good guide: [ https://css-tricks.com/creating-a-vs-code-theme/](url)

**Comment by jahnli** [comment]
Could you please help make this theme? I can make a donation

**Comment by rexebin** [comment]
I am sorry, very busy these days. It is easy to make the theme, give it a
try if you would.
